config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get "users/new"

  root to: 'static_pages#home'
  match 'createnewuser' => 'users#createnewuser'
  match 'addnewrow' => 'users#addnewrow'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::SecurePassword::InstanceMethodsOnActivation
  attr_accessible :password, :password_confirmation, :userName, :firstName, :lastName, :emailID, :roles
  has_secure_password
  
  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+.[A-Z]{2,4}$/i
  validates :emailID,   :presence => true, :format => EMAIL_REGEX
  validates :firstName, :presence => true
  validates :lastName,  :presence => true
  validates :userName,  :presence => true, :uniqueness => { case_sensitive: false}
  validates_uniqueness_of :userName, :emailID, :uniqueness => { case_sensitive: false}
  validates_length_of :userName, :within => 3..40
  validates_length_of :password, :on => :create, :in => 6..16
  validates_presence_of :password, :on => :create 
  validates_presence_of :password_confirmation, :on => :create 

  def is_admin?
    self.roles.gsub(" ","").split(',').include?('admin')    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    sign_out
  end 
  
  def create
    user = User.find_by_userName(params[:session][:userName])
    if user &&  user.authenticate(params[:session][:password]) && user.is_admin?
      sign_in user
      redirect_to users_url
    elsif user &&  user.authenticate(params[:session][:password])
      flash.now[:error] = "Need Admin privileges to login"
      render 'new'
    else
      flash.now[:error] = "Invalid username/password combo"
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def help
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :show, :destroy, :addnewrow, :createnewuser]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @users }
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    if request.post? and params[:user]
      @user = User.new(params[:user])

      respond_to do |format|
        if @user.save
          flash[:notice] = "User created."
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { respond_with(@user) }
          format.xml  { render :xml => @user, :status => :created, :location => @user }
        else
          format.html { render action: "new" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
          format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.json { respond_with_bip(@user) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@user) }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
      format.xml  { head :ok }
    end
  end

  def addnewrow
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Add new user details in table.' }
      format.xml { redirect_to users_url }
      format.js
    end

  end


  def createnewuser
    puts params.inspect
  @user = User.new
  @user.userName = params[:user][:userName]
  @user.firstName = params[:user][:firstName]
  @user.lastName = params[:user][:lastName]
  @user.emailID = params[:user][:emailID]
  @user.password = "foobar"
  @user.password_confirmation = "foobar"
   respond_to do |format|
        if @user.save
          format.html { redirect_to users_url }
          format.json { respond_with(@user) }
          format.xml  { render :xml => @user, :status => :created, :location => @user }
          format.js { render :js => "window.location.replace('#{article_path(@article)}');"}
        else
          format.html { redirect_to users_url }
          format.json { render json: @user.errors, status: :unprocessable_entity }
          format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        end
      end
  end

  private
  def signed_in_user
    redirect_to signin_url, notice: "Please sign in" unless signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Admin App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.id
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_id(cookies[:remember_token])
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
		Developed by <%= link_to "Vinay Chand", 'http://github.com/vinaychandvl/' %>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Admin App", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right navbar-inverse">
          <li class="divider-vertical"><%= link_to "Home",    root_path %></li>
          <li class="divider-vertical"><%= link_to "Help",    help_path %></li>					
					<% if signed_in? %>
						<li class="divider-vertical"><%= link_to "Users", users_path %></li>
						<li class="divider-vertical"><%= link_to "Sign out", signout_path, :method => "delete" %></li>
					<% else %>
          	<li class="divider-vertical"><%= link_to "Sign in", signin_path %></li>
					<% end %>	
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>SampleApp</title>
  		<%= stylesheet_link_tag    "application", :media => "all" %>
  		<%= javascript_include_tag "jquery-1.9.1","application" %>
  		<%= csrf_meta_tags %>
  		<%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="newalert">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>" id="elementstatus"><%= value %></div>
			<% end %>
      <%= yield %>
			<%#= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
	</body>
</html>

app/views/shared/_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_shared.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title,'About')%>
<h1>About</h1>
<p>
  This is the about page for the Admin application.
</p>

app/views/static_pages/help.html.erb
<% provide(:title,'Help')%>
<h1>Help</h1>
<p>
  A user can register with the site. Only a user with admin privileges can login and edit users.
</p>

app/views/static_pages/home.html.erb
<div class="container">  
  <header><h1>Login and Registration Form </h1></header>
  <section>				
    <div id="container_demo" >
      <div class="center hero-unit">
        <h1>Admin App</h1>
        <h2>This is the home page for the Admin application.</h2>
        <h4>Sign up to become a user</h4>
        <%= link_to "Sign Up now!", 'signup', class: "btn btn-large btn-primary" %>
        </br></br></br>
        Are you an admin? <%= link_to "Sign in", 'signin', class: "btn btn-small" %>
      </div>
    </div>
  </section>
</div>
<!--
    <a class="hiddenanchor" id="toregister"></a>
    <a class="hiddenanchor" id="tologin"></a>
    <div id="wrapper">
      <div id="login" class="animate form">
        <%= form_tag do %>
          <h1>Log in</h1> 
          <p> 
            <label for="username" class="uname" data-icon="u" > Your email or username </label>
            <input id="username" name="username" required="required" type="text" placeholder="myusername or mymail@mail.com"/>
          </p>
          <p> 
            <label for="password" class="youpasswd" data-icon="p"> Your password </label>
            <input id="password" name="password" required="required" type="password" placeholder="eg. X8df!90EO" /> 
          </p>
          <p class="keeplogin">
            <input type="checkbox" name="loginkeeping" id="loginkeeping" value="loginkeeping" /> 
            <label for="loginkeeping">Keep me logged in</label>
          </p>
          <p class="login button"> 
          <%= submit_tag "Submit" %>
          </p>
          <p class="change_link">
            Not a member yet ?
            <a href="#toregister" class="to_register">Join us</a>
          </p>
         <%  end %>
        </div>
        <div id="register" class="animate form">
          <%= form_tag  do %>
            <h1> Sign up </h1>
            <p> 
              <label for="usernamesignup" class="uname" data-icon="u">Your username</label>
              <input id="usernamesignup" name="usernamesignup" required="required" type="text" placeholder="myusername" />
            </p>
            <p> 
              <label for="firstnamesignup" class="fname" data-icon="u">Your username</label>
              <input id="firstnamesignup" name="firstnamesignup" required="required" type="text" placeholder="myfirstname" />
            </p>
            <p> 
              <label for="lastnamesignup" class="lname" data-icon="u">Your username</label>
              <input id="lastnamesignup" name="lastnamesignup" required="required" type="text" placeholder="mylastname" />
            </p>
            <p> 
              <label for="emailsignup" class="youmail" data-icon="e" > Your email</label>
              <input id="emailsignup" name="emailsignup" required="required" type="email" placeholder="mysupermail@mail.com"/> 
            </p>
            <p> 
              <label for="rolesignup" class="yourole" > Your role</label>
              <select id="rolesignup" title ="rolesignup" name="rolesignup" size="2" multiple="multiple">
              <option name=admin value=admin> admin </option>
              <option name=basic value=basic> basic </option>
              <option name=power value=power> power </option>
              <option name=super value=super> super </option>
              </select>
            </p>
            <p> 
              <label for="passwordsignup" class="youpasswd" data-icon="p">Your password </label>
              <input id="passwordsignup" name="passwordsignup" required="required" type="password" placeholder="eg.X8df!90EO"/>
            </p>
            <p> 
              <label for="passwordsignup_confirm" class="youpasswd" data-icon="p">Please confirm your password </label>
              <input id="passwordsignup_confirm" name="passwordsignup_confirm" required="required" type="password" placeholder="eg. X8df!90EO"/>
            </p>
            <p class="signin button"> 
              <%= submit_tag "Signup" %>
            </p>
            <p class="change_link">  
              Already a member ?
              <a href="#tologin" class="to_register"> Go and log in </a>
            </p>
          <%  end %>
        </div>			
      </div>
    </div>  
  </section>
</div>
-->

app/views/users/_form.html.erb
<tr>
  <%= form_for @user=User.new, :url => { :action => 'createnewuser' } do |f| %>
    <td></td>
    <td><%= f.text_field :userName%></td>
    <td><%= f.text_field :firstName%></td>
    <td><%= f.text_field :lastName%></td>
    <td><%= f.text_field :emailID%></td>
    <td><%= f.text_field :roles%></td>
    <td></td>
    <td></td>
    <td><%= submit_tag 'Save', :class => 'button_link' %></td>
  <% end %>
</tr>

app/views/users/_form.js.erb
<tr>
  <%= form_for @user=User.new, :url => { :action => 'createnewuser' } do |f| %>
    <td></td>
    <td><%= f.text_field :userName%></td>
    <td><%= f.text_field :firstName%></td>
    <td><%= f.text_field :lastName%></td>
    <td><%= f.text_field :emailID%></td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= submit_tag 'Save', :class => 'button_link' %></td>
  <% end %>
</tr>

app/views/users/addnewrow.js.erb
$("#usertable > tbody > tr:first").before("<%=escape_javascript(render(:partial => 'form'))%>");
$("#newalert").prepend("<div class = 'alert'>Add new user details in table</div>");

app/views/users/edit.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<div class="container">  
  <header><h1> USER DETAILS </h1></header>
  <section>				
  <div id="container_demo" >
    <div id="wrapper">
      <div id="login" class="animate form">
          <%= form_for @user, :url => { :action => "update" } do |f| %>
            <h1> EDIT USER </h1>
            <%= render 'shared/errors' %>
            <p> 
              <label for="usernamesignup" class="uname" data-icon="u">Your User Name</label>
              <%= f.text_field :userName%>
            </p>
            <p> 
              <label for="firstnamesignup" class="fname" data-icon="u">Your First Name</label>
              <%= f.text_field :firstName%>
            </p>
            <p> 
              <label for="lastnamesignup" class="lname" data-icon="u">Your Last Name</label>
              <%= f.text_field :lastName%>
            </p>
            <p> 
              <label for="emailsignup" class="youmail" data-icon="e" > Your email</label>
              <%= f.text_field :emailID%>
            </p>
            <p> 
              <label for="rolesignup" class="yourole" data-icon="u" > Your role</label>
              <%= f.text_field :roles%>	
            </p>
            <p> 
            <p class="signin button"> 
              <%= submit_tag "Submit" %>
            </p>  
          <% end %>
        	<%= button_to 'Back', users_path, :class => "button_link", :method => "get" %>
          <%= button_to 'Delete', {:action => "destroy", :id => @user.id}, :class => "button_link", :confirm => "Are you sure?", :method => "delete" %>
        </div>		
      </div>
    </div>  
  </section>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'Users') %>
<p id="notice"><%= notice %></p>
<div class="container">  
  <header><h1>Listing users</h1></header>
  <section>
    <%= button_to "Add User", addnewrow_path, :class => "button_link", :remote => true  %>
  <div id="container_demo" >
  <table cellpadding="0" cellspacing="0" border="0" class="display" id="usertable">
    <thead>
      <tr>
        <th>User ID</th>
        <th>User Name</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email ID</th>
        <th>Roles</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
          <tr id="user_<%= user.id %>">
            <td><%= user.id%></td>
            <td><%= best_in_place user, :userName%></td>
            <td><%= best_in_place user, :firstName%></td>
            <td><%= best_in_place user, :lastName%></td>
            <td><%= best_in_place user, :emailID%></td>
            <td><%= best_in_place user, :roles%></td>
            <td><%= button_to 'Show', user, :class => "button_link", :method => "get"  %></td>
            <td><%= button_to 'Edit', edit_user_path(user), :class => "button_link", :method => "get"  %></td>
            <td><%= button_to 'Delete', {:action => "destroy", :id => user.id}, :class => "button_link", :confirm => "Are you sure?", :method => "delete" %></td>
          </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <th><input type="hidden"/></th>
        <th><input type="text" name="search_userName" value="Search User Names" class="search_init" /></th>
        <th><input type="text" name="search_emailID" value="Search Email ID" class="search_init" /></th>
        <th><input type="text" name="search_firstName" value="Search First Names" class="search_init" /></th>
        <th><input type="text" name="search_lastName" value="Search Last Names" class="search_init" /></th>
        <th><input type="text" name="search_roles" value="Search Roles" class="search_init" /></th>
        <th></th>
        <th></th>
        <th><%= button_to 'New User', new_user_path, :class => "button_link", :method => "get" %></th>
      </tr>
     </tfoot>
  </table>
  </div>
  </section>
</div>

app/views/users/new.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<div class="container">  
  <section>				
  <div id="container_demo" >
    <div id="wrapper">
      <div id="login" class="animate form">
          <%= form_for @user, :url => { :action => "create" } do |f| %>
            <h1> CREATE NEW USER </h1>
            <%= render 'shared/errors' %>
            <p> 
              <label for="usernamesignup" class="uname" data-icon="u">Your User Name</label>
              <%= f.text_field :userName%>
            </p>
            <p> 
              <label for="firstnamesignup" class="fname" data-icon="u">Your First Name</label>
              <%= f.text_field :firstName%>
            </p>
            <p> 
              <label for="lastnamesignup" class="lname" data-icon="u">Your Last Name</label>
              <%= f.text_field :lastName%>
            </p>
            <p> 
              <label for="emailsignup" class="youmail" data-icon="e" > Your email</label>
              <%= f.text_field :emailID%>
            </p>
            <p> 
              <label for="rolesignup" class="yourole" data-icon="u"> Your role</label>
              	<%= f.text_field :roles%>
            </p>
            <p> 
              <label for="passwordsignup" class="youpasswd" data-icon="p">Your password </label>
              <%= f.password_field :password%>
            </p>
            <p> 
              <label for="passwordsignup_confirm" class="youpasswd" data-icon="p">Please confirm your password </label>
              <%= f.password_field :password_confirmation%> 
            </p>
            <p class="signin button"> 
              <%= submit_tag "Submit" %>
            </p>  
          <% end %>

          <p>Existing User? <%= link_to "Sign in now", signin_path %></p>
        </div>		
      </div>
    </div>  
  </section>
</div>

app/views/users/show.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<div class="container">  
  <header><h1> SHOW USER DETAILS </h1></header>
  <section>
  <div id="container_demo" >
  <table cellpadding="0" cellspacing="0" border="0" class="display" id="usertable">
    <thead>
      <tr>
        <th> User ID   </th>
        <th> User Name </th>
        <th> Email ID  </th>
        <th> First Name</th>
        <th> Last Name </th>
        <th> Roles     </th>
        <th> Edit      </th>
        <th> Back      </th>
        <th> Back      </th>
      </tr>
    </thead>
    <tbody>
      <tr id="user_<%= @user.id %>">
            <td><%=@user.id%></td>
            <td><%= best_in_place @user, :userName, :type => :input%></td>
            <td><%= best_in_place @user, :emailID, :type => :input%></td>
            <td><%= best_in_place @user, :firstName, :type => :input%></td>
            <td><%= best_in_place @user, :lastName, :type => :input%></td>
            <td><%= best_in_place @user, :roles, :type => :input%></td>
        <td><%= button_to 'Edit', edit_user_path(@user), :class => "button_link", :method => "get"  %></td>
        <td><%= button_to 'Back', users_path, :class => "button_link", :method => "get"  %></td>
        <td><%= button_to 'Delete', {:action => "destroy", :id => @user.id}, :class => "button_link", :confirm => "Are you sure?", :method => "delete" %></td>
      </tr>
    </tbody>
  </table>
  </div>
  </section>
</div>